TARGET = bin/project
SRC = $(wildcard src/*.c)
OBJ = $(patsubst src/%.c, obj/%.o, $(SRC))

$(TARGET): $(OBJ)
	gcc -o $@ $?

bin/%.o: src/%.c
	gcc -c $< -o $@ -Iinc

clean:
	rm -f $(TARGET)
	rm -f bin/%.o
